### ISSUE TITLE
Report bugs in xtext gradle plugin

### ISSUE THREAD

**Issue by alexandrebouchard** [UBC-Stat-ML/blangSDK#56]
Most critical seems related to problems in resolution of cycles. Another one is xtend calling static function declared in java interface which should be ok in Java 8. Another one is with static inner classes in xtend.

See e.g. 37d49e966bb7c9a8bce73b45bc364947405c0953 for an example of the first two.

**Comment by alexandrebouchard** [comment]
For the static inner stuff, fixed in 2.11:

https://github.com/eclipse/xtext-extras/issues/30

**Comment by alexandrebouchard** [comment]
Commit f4735db was still not enough (on amazon; ok on mac and travis (which failed for different reasons))

New hypothesis for the "circular dependency issue" seems to be that the auto-import of e.g. blang.distribution does not work correctly at least for things like Normal.distribution(..)

**Comment by alexandrebouchard** [comment]
Situation is getting weirder and weirder

- Still the case that compilation work on mac, travis, but not ec2 (travis fails for other reasons, another bug to fix next with non-determinism of test case + smelly test case with slice sampler)
- Why would they behave differently? Same issue with ./gradlew or emptying the caches
- Bunch of workaround did not work. (see commits of Oct 26). Stubborn problem.

**Comment by alexandrebouchard** [comment]
For reference, the 2 outputs

[output-from-ec2.txt](https://github.com/UBC-Stat-ML/blangSDK/files/1420928/output-from-ec2.txt)

[output-from-mac.txt](https://github.com/UBC-Stat-ML/blangSDK/files/1420931/output-from-mac.txt)

**Comment by alexandrebouchard** [comment]
Looks like set of things downloaded is not the same. Investigate.

**Comment by alexandrebouchard** [comment]
Done. 

https://github.com/xtext/xtext-gradle-plugin/issues/98 

Waiting for now. 

Could be the two pass thing. But seems unlikely as I think the lambda already takes care of being lazy (double check). If so, remove some of the recent changes.

**Comment by alexandrebouchard** [comment]
Some suggestions/ideas so far:

- notify existence of inner static classes at pre-indexing time 
  - move them to first order classes in an internal package? seems might make problem worse with many more dependencies across
- is the problem with static generated methods?

**Comment by alexandrebouchard** [comment]
Think about whether this eclipse output (which is overcame apparently as things eventually compile) is relevant:

```
!STACK 0
java.lang.IllegalArgumentException: The type blang.core.DeboxedName is not on the classpath.
	at org.eclipse.xtext.xbase.jvmmodel.JvmAnnotationReferenceBuilder.annotationRef(JvmAnnotationReferenceBuilder.java:83)
	at org.eclipse.xtext.xbase.jvmmodel.JvmAnnotationReferenceBuilder.annotationRef(JvmAnnotationReferenceBuilder.java:60)
	at ca.ubc.stat.blang.jvmmodel.SingleBlangModelInferrer$13.apply(SingleBlangModelInferrer.java:834)
	at ca.ubc.stat.blang.jvmmodel.SingleBlangModelInferrer$13.apply(SingleBlangModelInferrer.java:1)
	at org.eclipse.xtext.xbase.jvmmodel.JvmTypesBuilder.initializeSafely(JvmTypesBuilder.java:211)
	at org.eclipse.xtext.xbase.jvmmodel.JvmTypesBuilder.toConstructor(JvmTypesBuilder.java:857)
	at ca.ubc.stat.blang.jvmmodel.SingleBlangModelInferrer.generateConstructor(SingleBlangModelInferrer.java:880)
	at ca.ubc.stat.blang.jvmmodel.SingleBlangModelInferrer.infer(SingleBlangModelInferrer.java:183)
	at ca.ubc.stat.blang.jvmmodel.BlangDslJvmModelInferrer$1.apply(BlangDslJvmModelInferrer.java:81)
	at ca.ubc.stat.blang.jvmmodel.BlangDslJvmModelInferrer$1.apply(BlangDslJvmModelInferrer.java:1)
	at org.eclipse.xtext.xbase.jvmmodel.JvmModelAssociator$1.run(JvmModelAssociator.java:397)
	at org.eclipse.xtext.xbase.jvmmodel.JvmModelAssociator.installDerivedState(JvmModelAssociator.java:407)
	at org.eclipse.xtext.resource.DerivedStateAwareResource.installDerivedState(DerivedStateAwareResource.java:242)
	at org.eclipse.xtext.xbase.resource.BatchLinkableResource.getContents(BatchLinkableResource.java:148)
	at org.eclipse.emf.ecore.resource.impl.ResourceImpl.getEObjectForURIFragmentRootSegment(ResourceImpl.java:721)
	at org.eclipse.xtext.resource.DerivedStateAwareResource.getEObjectForURIFragmentRootSegment(DerivedStateAwareResource.java:211)
	at org.eclipse.emf.ecore.resource.impl.ResourceImpl.getEObject(ResourceImpl.java:763)
	at org.eclipse.emf.ecore.resource.impl.ResourceImpl.getEObject(ResourceImpl.java:742)
	at org.eclipse.xtext.resource.XtextResource.access$101(XtextResource.java:63)
	at org.eclipse.xtext.resource.XtextResource$1.getEObject(XtextResource.java:119)
	at org.eclipse.xtext.resource.DefaultFragmentProvider.getEObject(DefaultFragmentProvider.java:28)
	at org.eclipse.xtext.resource.XtextResource.basicGetEObject(XtextResource.java:363)
	at org.eclipse.xtext.resource.XtextResource.getEObject(XtextResource.java:349)
	at org.eclipse.xtext.linking.lazy.LazyLinkingResource.getEObject(LazyLinkingResource.java:232)
	at org.eclipse.xtext.resource.persistence.StorageAwareResource.getEObject(StorageAwareResource.java:120)
	at org.eclipse.xtext.xbase.resource.BatchLinkableResource.getEObject(BatchLinkableResource.java:124)
	at org.eclipse.emf.ecore.resource.impl.ResourceSetImpl.getEObject(ResourceSetImpl.java:223)
	at org.eclipse.emf.ecore.util.EcoreUtil.resolve(EcoreUtil.java:201)
	at org.eclipse.emf.ecore.util.EcoreUtil.resolve(EcoreUtil.java:223)
	at org.eclipse.emf.ecore.util.EcoreUtil.resolve(EcoreUtil.java:261)
	at org.eclipse.emf.ecore.impl.BasicEObjectImpl.eResolveProxy(BasicEObjectImpl.java:1477)
	at ca.ubc.stat.blang.blangDsl.impl.BlangDistImpl.getDistributionType(BlangDistImpl.java:73)
	at ca.ubc.stat.blang.jvmmodel.SingleBlangModelInferrer._constructorParameters(SingleBlangModelInferrer.java:1245)
	at ca.ubc.stat.blang.jvmmodel.SingleBlangModelInferrer.constructorParameters(SingleBlangModelInferrer.java:1395)
	at ca.ubc.stat.blang.jvmmodel.SingleBlangModelInferrer._instantiateFactor(SingleBlangModelInferrer.java:1191)
	at ca.ubc.stat.blang.jvmmodel.SingleBlangModelInferrer.instantiateFactor(SingleBlangModelInferrer.java:1373)
	at ca.ubc.stat.blang.jvmmodel.SingleBlangModelInferrer.access$13(SingleBlangModelInferrer.java:1369)
	at ca.ubc.stat.blang.jvmmodel.SingleBlangModelInferrer$20.appendTo(SingleBlangModelInferrer.java:1133)
	at org.eclipse.xtend2.lib.StringConcatenation.append(StringConcatenation.java:198)
	at org.eclipse.xtend2.lib.StringConcatenation$SimpleTarget.append(StringConcatenation.java:697)
	at ca.ubc.stat.blang.jvmmodel.SingleBlangModelInferrer$18.appendTo(SingleBlangModelInferrer.java:1022)
	at org.eclipse.xtend2.lib.StringConcatenation.append(StringConcatenation.java:176)
	at org.eclipse.xtend2.lib.StringConcatenation.append(StringConcatenation.java:277)
	at ca.ubc.stat.blang.StaticUtils.eagerlyEvaluate(StaticUtils.java:86)
	at ca.ubc.stat.blang.jvmmodel.SingleBlangModelInferrer.infer(SingleBlangModelInferrer.java:176)
	at ca.ubc.stat.blang.jvmmodel.BlangDslJvmModelInferrer$1.apply(BlangDslJvmModelInferrer.java:81)
	at ca.ubc.stat.blang.jvmmodel.BlangDslJvmModelInferrer$1.apply(BlangDslJvmModelInferrer.java:1)
	at org.eclipse.xtext.xbase.jvmmodel.JvmModelAssociator$1.run(JvmModelAssociator.java:397)
	at org.eclipse.xtext.xbase.jvmmodel.JvmModelAssociator.installDerivedState(JvmModelAssociator.java:407)
	at org.eclipse.xtext.resource.DerivedStateAwareResource.installDerivedState(DerivedStateAwareResource.java:242)
	at org.eclipse.xtext.xbase.resource.BatchLinkableResource.getContents(BatchLinkableResource.java:148)
	at org.eclipse.xtext.xtext.ecoreInference.Xtext2EcoreTransformer.removeGeneratedPackages(Xtext2EcoreTransformer.java:163)
	at org.eclipse.xtext.xtext.XtextLinker.linkModel(XtextLinker.java:255)
	at org.eclipse.xtext.resource.XtextResource.doLinking(XtextResource.java:340)
	at org.eclipse.xtext.linking.lazy.LazyLinkingResource.doLinking(LazyLinkingResource.java:107)
	at org.eclipse.xtext.xtext.GrammarResource.superDoLinking(GrammarResource.java:48)
	at org.eclipse.xtext.xtext.GrammarResource$LinkingTrigger.installDerivedState(GrammarResource.java:95)
	at org.eclipse.xtext.resource.DerivedStateAwareResource.installDerivedState(DerivedStateAwareResource.java:242)
	at org.eclipse.xtext.resource.DerivedStateAwareResource.getContents(DerivedStateAwareResource.java:97)
	at org.eclipse.emf.ecore.util.EcoreUtil.getAllContents(EcoreUtil.java:1178)
	at org.eclipse.xtext.linking.lazy.LazyLinkingResource.resolveLazyCrossReferences(LazyLinkingResource.java:125)
	at org.eclipse.xtext.EcoreUtil2.resolveLazyCrossReferences(EcoreUtil2.java:498)
	at org.eclipse.xtext.builder.clustering.ClusteringBuilderState.doUpdate(ClusteringBuilderState.java:230)
	at org.eclipse.xtext.builder.builderState.AbstractBuilderState.update(AbstractBuilderState.java:116)
	at org.eclipse.xtext.builder.impl.XtextBuilder.doBuild(XtextBuilder.java:287)
	at org.eclipse.xtext.builder.impl.XtextBuilder.fullBuild(XtextBuilder.java:319)
	at org.eclipse.xtext.builder.impl.XtextBuilder.build(XtextBuilder.java:155)
	at org.eclipse.core.internal.events.BuildManager$2.run(BuildManager.java:735)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:42)
	at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:206)
	at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:246)
	at org.eclipse.core.internal.events.BuildManager$1.run(BuildManager.java:301)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:42)
	at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:304)
	at org.eclipse.core.internal.events.BuildManager.basicBuildLoop(BuildManager.java:360)
	at org.eclipse.core.internal.events.BuildManager.build(BuildManager.java:383)
	at org.eclipse.core.internal.events.AutoBuildJob.doBuild(AutoBuildJob.java:142)
	at org.eclipse.core.internal.events.AutoBuildJob.run(AutoBuildJob.java:232)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:56)
```
