### ISSUE TITLE
Test case for RealSliceSampler fails

### ISSUE THREAD

**Issue by alexandrebouchard** [UBC-Stat-ML/blangSDK#62]
Needs to crank up to 1000 kernels applications. Try it on SimpleHierarchicalModel, get:

```
Corrected pValue = 0.0025
Exception in thread "main" java.lang.AssertionError: Some test(s) failed:
SimpleHierarchicalModel	RealSliceSampler	TestSDKDistributions$$Lambda$6/859417998	1.7158139124129335E-4	0.5000648817555866(0.0028731525502088203)	0.4875457908615822(0.002790078798663967)
	at org.junit.Assert.fail(Assert.java:88)
	at blang.validation.ExactInvarianceTest.check(ExactInvarianceTest.java:145)
	at blang.validation.ExactInvarianceTest.check(ExactInvarianceTest.java:138)
	at blang.TestSDKDistributions.test(TestSDKDistributions.java:77)
	at blang.TestSDKDistributions.test(TestSDKDistributions.java:27)
	at blang.TestSDKDistributions.main(TestSDKDistributions.java:32)

```

**Comment by alexandrebouchard** [comment]
See TestDeep

**Comment by alexandrebouchard** [comment]
Notes so far:

- Perhaps problem is numerical precision asymmetry. Can be investigated via Dirichlet: should have same behaviour with asymmetric strategy (each but last and last) and not with symmetrized strategy (each with next modulo).
  - First needed to write slice Dirichlet sampler, just MH was too slow to get enough power in reasonable time.
  - Encountered limitation in the way the Dirichlet was implemented. See #65 Workaround implemented.
  - Need to change deep test case to sample everything for fairness

**Comment by alexandrebouchard** [comment]
- OK, commit 823ce2c07a67335dfd33bc767bc8f038e9a3cfaa seems to support this
- However this was with t test; KS test still fails
- Once this is sorted out, refactor Beta into a special case of Dirichlet with same strategy as Exponential/Gamma

**Comment by alexandrebouchard** [comment]
- Now the problem is more subtle. A tail-only issue detectable only with KS or 3rd moment. (and seems real, looking at QQ plots).
- Implemented underflow-resilient Dirichlet generation. Seems to work but does not solve the issue. Needs more testing too later on.
- Now strangely the only test failing is Deep_Diri, Deep_Beta is OK...

```
java.lang.AssertionError: Some test(s) failed (samples saved in /Users/bouchard/w/blangSDK/failed-test-info-1510211963293):
Deep_Diri	ALL	Examples$$Lambda$61/1642030774	4.54111531296153E-5	0.20526311271301784(0.002100355350344907)	0.19545836224036917(0.0019516011921039411)
```

**Comment by alexandrebouchard** [comment]
OK Deep_Beta is failing too once setting back concentration to 0.1

**Comment by alexandrebouchard** [comment]
Some weird thing going on with the gamma function? Try the same model on JAGS?

**Comment by alexandrebouchard** [comment]
Might be worth double-checking (via higher moments) that it's not the forward simulation that's actually off.

**Comment by alexandrebouchard** [comment]
Not very consistent with the symmetrization observations. Really looks like a problem on one end of the simplex which is symmetrized by the new Dirichlet sampler.

**Comment by alexandrebouchard** [comment]
OK moments seem fine. Next thing to check might be  normalization via numeric integration.

**Comment by alexandrebouchard** [comment]
OK, probably the asymptote to INF encountered in sparse Dirichlet/Beta. E.g. test case for normalization easy for dense Dirichlet but numerically challenged for sparse ones.

**Comment by alexandrebouchard** [comment]
Cause could be the uniform in the slice sampler is not 'centered' around current point. So some weird precision thing could be happening.

**Comment by alexandrebouchard** [comment]
### Updates

- Problem can be replicated with simpler test case. In 9b6686446e9c5cf5dba05d64071fa87acd2a08b7 see TestDeep, 
  - For a ``Beta(0.1,0.1)``:
```
Beta 	RealSliceSampler 	Examples$$Lambda$44/1860513229 	0.009193551941572009 	0.5047990514772717(0.004587010342391204) 	0.5081834044347415(0.004576215474464481) 	0.882299999999999
```
  - For a ``Dir(0.1,0.1)``:
```
Dirichlet 	SimplexSampler 	Examples$$Lambda$45/532854629 	0.004481700042825332 	0.49310580152149064(0.004553534706491196) 	0.5102641731587164(0.00456237716340777) 	0.9730999999999981
```

### Conclusions

There is mounting evidence that it's just a numerical issue caused by the asymptotes. 

- Normalization hard to compute in TestNormalization
- Just by looking at density in log log scale for Beta(0.1,0.1) vs Beta(0.01, 0.01) crosses at 10e-12 i.e. mass is very close to the boundaries
[loglog.pdf](https://github.com/UBC-Stat-ML/blangSDK/files/1460592/loglog.pdf)
- Potential related reports
  - Similar problem in JAGS? https://sourceforge.net/p/mcmc-jags/discussion/610037/thread/c21ef62a/
  - Similar problem in Stan? https://groups.google.com/forum/#!msg/stan-users/Q1ZDhlGPZyc/AVuX_7pEdSsJ

### Strategy

- Warning message once when using small values
- Do migrate Beta into Dirichlet to benefit from nice sampler
- Close this issue asap
